### ISSUE TITLE
Error while installing with CocoaPods

### ISSUE THREAD

**Issue by hemangshah** [rushisangani/BiometricAuthentication#5]
Hi Rushi, first of all, great work. I tried to install it using CocoaPods and it's giving me this error.

Specs satisfying the `BiometricAuthentication (= 1.0.0)` dependency were found, but they required a higher minimum deployment target.

> For my app, the deployment target is 9.0.

**I need to ask you whether it will work with 9.0 or not? And if not, if I change my deployment target to 10.0 will my app install on the devices having lesser than 10.0?**

**Comment by hemangshah** [comment]
Clearly, you have mentioned iOS 10.0 is requirements. I am closing this for now.

**Comment by rushisangani** [comment]
Hi @hemangshah, only 9% of total ios devices are running iOS 9. And this will reduce once most of the users migrate to iOS 11. You can surely remove support for iOS 9.

Thanks.

**Comment by hemangshah** [comment]
@rushisangani Yes, thanks for letting me know.

**Comment by hemangshah** [comment]
@rushisangani, can't you change it for iOS 9.0? I don't think, it will stop the library?

**Comment by rushisangani** [comment]
@hemangshah, Apple has made changes in the LocalAuthentication framework in each ios version since iOS 8.0.
There are some properties & enums which they've modified in iOS 10 as well as to support Face ID they've deprecated some property and declares a new one in iOS 11.

So that's the reason I set a minimum target to iOS 10.
And also to test in iOS 9.0, you have to work on older version of Xcode, if you do not have iOS 9 devices.

**Comment by hemangshah** [comment]
@rushisangani  FYR, I can run the Swift 4.x app in iOS 9.0 and Xcode 9.1.0

**Comment by rushisangani** [comment]
@hemangshah, iOS 9.0 is supported now.
Please update your pod to the latest version **BiometricAuthentication (1.0.1)**

**Comment by hemangshah** [comment]
@rushisangani, thank you so much! 👍
